language: java
jdk: oraclejdk8

cache:
  directories:
    - node_modules
    - $HOME/.m2

services:
  - mysql
#  - neo4j

before_install:
  - mysql -e 'CREATE DATABASE gutenberg;'

script:
  - mvn verify
